### ISSUE TITLE
Замена NS серверов для домена terratensor.ru

### ISSUE THREAD

**Issue by audetv** [audetv/cohesion#9]
В спокойном режиме, не срочно надо будет изменить у регистратора домена terratensor.ru ns записи
Ранее вы указывали ns сервера для домена terratensor.ru в панели управления доменом.

Сообщение от Selectel:
> Мы будем отказываться от старых NS-серверов. Позднее они перестанут быть доступными, к таким работам отправим вам дополнительное уведомление.
> 
> Рекомендуем уже сейчас изменить NS-записи со стороны регистратора домена на актуальные:
> 
> ns1.selectel.ru (ранее ns1.selectel.org)
> ns2.selectel.ru (ранее ns2.selectel.org)
> ns3.selectel.ru (ранее ns3.selectel.org)
> ns4.selectel.ru (ранее ns4.selectel.org)
> Изменение не затронет доступность домена.
> 

Надо заменить на:
 ns1.selectel.ru (ранее ns1.selectel.org)
 ns2.selectel.ru (ранее ns2.selectel.org)
 ns3.selectel.ru (ранее ns3.selectel.org)
 ns4.selectel.ru (ранее ns4.selectel.org)

**Comment by iprst** [comment]
Заменил.
